version: '2'
services:
  data:
    container_name: 'data'
    image: busybox
    volumes: 
      - ./data/www:/var/www
      - ./logs/httpd:/var/log/httpd

  web_httpd:
    container_name: 'httpd'
    image: oshou/docker-centos7-httpd24:latest
    volumes_from:
      - data
    ports:
      - 80:80
      - 443:443
